services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      LEVEL: "alexs_christian_realm_future_past_present_tense"
    volumes:
      - ./data:/data
    restart: unless-stopped
